### ISSUE TITLE
VM crashes when i try to create a Bot in Fedora 32

### ISSUE THREAD

**Issue by lucianomartinez27** [pablo1n7/bottlegram#4]
I've found a problem for Fedora 32. When i tried to create a Bot the VM crashes, and the output in the terminal was:

`stack page bytes 8192 available headroom 5576 minimum unused headroom 5952
(Segmentation fault).` among other things.

The solution i've found was replace http://libgit2.so in pharo-vm with the system one:

Install http://libgit2.so.1.0 with dnf install libgit2
cp /usr/lib64/libgit2.so.1.0 ~/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so

And there should work, although I don't know how does it work.

**Comment by pablo1n7** [comment]
Thank you for report the problem and the solution.
